[project]
name = "stockportfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "psycopg2>=2.9.11",
    "werkzeug>=3.1.4",
    "yfinance>=0.2.66",
]
